### ISSUE TITLE
Output of _toc.rst and generated ToC are different

### ISSUE THREAD

**Issue by ktbartholomew** [deconst/preparer-sphinx#68]
When using `_toc.rst`, Sphinx generates a `<div class="toctree-wrapper">` element surrounding the table of contents. When using the generated table of contents from `index.rst`, this wrapping element is not present. Whether including the wrapping element or not, the two methods of generating the table of contents should produce the same output.

**Comment by smashwilson** [comment]
I'm opting to add the wrapping element to the generated tables of contents. `_toc.rst` is intended to let you add "arbitrary markup", which makes me hesitant to mess with the HTML it builds; technically you don't even need to have a `.. toctree` in there.
